### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by shuvashish76** [gdzx/audiosource#4]
I simply installed the app & when opened it crashes.

### Logs:
```
FATAL EXCEPTION: main
Process: fr.dzx.audiosource, PID: 22627
java.lang.RuntimeException: Unable to resume activity {fr.dzx.audiosource/fr.dzx.audiosource.MainActivity}: java.lang.IllegalStateException: Activity {fr.dzx.audiosource/fr.dzx.audiosource.MainActivity} did not call finish() prior to onResume() completing
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Activity {fr.dzx.audiosource/fr.dzx.audiosource.MainActivity} did not call finish() prior to onResume() completing
	at android.app.Activity.performResume(Activity.java:7314)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
	... 11 more
```
Followed by another crash

```
FATAL EXCEPTION: main
Process: fr.dzx.audiosource, PID: 22822
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=audiosource pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PUBLIC)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Device details:
Model : Lenovo TB-8704X
Android : 9
App version : 1.0 (1)

**Comment by gdzx** [comment]
Hi !

Thank you for your report.

I made a version that includes Android 8 and up when creating a notification channel which may fix the second exception (and hopefully also the first):

```diff
@@ -43,9 +43,9 @@ public class RecordService extends Service {
-        if (Build.VERSION.SDK_INT >= 29) {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
             NotificationChannel channel = new NotificationChannel(CHANNEL_ID,
```

Could you try with this change by uninstalling your current version and installing the `app-debug.apk` from [app-debug.zip](https://github.com/gdzx/audiosource/files/14232967/app-debug.zip) ?

Best regards

**Comment by shuvashish76** [comment]
Still crashes
<details><summary>Logs</summary>
<p>

```
FATAL EXCEPTION: main
Process: fr.dzx.audiosource, PID: 27209
java.lang.RuntimeException: Unable to resume activity {fr.dzx.audiosource/fr.dzx.audiosource.MainActivity}: java.lang.IllegalStateException: Activity {fr.dzx.audiosource/fr.dzx.audiosource.MainActivity} did not call finish() prior to onResume() completing
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Activity {fr.dzx.audiosource/fr.dzx.audiosource.MainActivity} did not call finish() prior to onResume() completing
	at android.app.Activity.performResume(Activity.java:7314)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
	... 11 more
```
```
FATAL EXCEPTION: main
Process: fr.dzx.audiosource, PID: 28295
java.lang.NoSuchMethodError: No virtual method startForeground(ILandroid/app/Notification;I)V in class Lfr/dzx/audiosource/RecordService; or its super classes (declaration of 'fr.dzx.audiosource.RecordService' appears in /data/app/fr.dzx.audiosource-lz9j9mztRyRAukO5s5VZlw==/base.apk)
	at fr.dzx.audiosource.RecordService.onCreate(RecordService.java:51)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3570)
	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

</p>
</details> 

App version: 1.1-debug (2)

**Comment by gdzx** [comment]
Ok, let's try the following changes:

```diff
M app/src/main/AndroidManifest.xml
@@ -10,7 +10,7 @@
         android:icon="@mipmap/ic_launcher"
         android:label="@string/app_name"
         android:roundIcon="@mipmap/ic_launcher_round"
-        android:theme="@android:style/Theme.NoDisplay">
+        android:theme="@android:style/Theme.Translucent.NoTitleBar">
         <activity
             android:name="fr.dzx.audiosource.MainActivity"
             android:showWhenLocked="true"
M app/src/main/java/fr/dzx/audiosource/RecordService.java
@@ -43,11 +43,13 @@ public class RecordService extends Service {
 
         Notification notification = createNotificationStarting();
 
-        if (Build.VERSION.SDK_INT >= 29) {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
             NotificationChannel channel = new NotificationChannel(CHANNEL_ID,
                     getString(R.string.app_name), NotificationManager.IMPORTANCE_NONE);
             getNotificationManager().createNotificationChannel(channel);
+        }
 
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
             startForeground(NOTIFICATION_ID, notification,
                     ServiceInfo.FOREGROUND_SERVICE_TYPE_NONE);
         } else {
```

Same as the previous APK: [app-debug.zip](https://github.com/gdzx/audiosource/files/14233747/app-debug.zip)

**Comment by shuvashish76** [comment]
Thanks now the app works, no crashes. I'll check in the morning.
I haven't really checked on PC. if everything goes well I'll close the issue.

I installed this app to test audio quality for http://librivox.org/.
ThankYou.

**Comment by shuvashish76** [comment]
How do I start it?
I'm on EndeavourOS, [android-tools](https://archlinux.org/packages/extra/x86_64/android-tools/) installed from Arch repository.

**Comment by shuvashish76** [comment]
Please do make a release for Izzy to pick it up for his repo.
https://apt.izzysoft.de/fdroid/index/apk/fr.dzx.audiosource
